php:
  build: .
  ports: 
    - "80:80"
    - "443:443"
  volumes:
    - ./www/CursoPHP/:/var/www/html
  links:
    - db
db:
  image: postgres:11.1-alpine
  working_dir: /application
  volumes:
    - .:/application
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=livro
  ports:
    - "5432:5432"